@startuml
充值提现模块 -> 收银台:发起线上充值
收银台 -> 第三方支付模块 :发起三方支付
note over 第三方支付模块
          等待用户支付,省略支付过程
end note
第三方支付模块 -> 收银台 :返回支付结果
group 第三方支付结算
收银台 -> 结算模块:第三方支付结算指令
结算模块 -> 银行支付模块 :发起银行支付[1]
note over 银行支付模块
          等待银行支付,省略银行网关
end note
结算模块 <- 银行支付模块 :返回支付结果
结算模块 -> 银行支付模块 :请求银行出账和入账流水[1]
note over 银行支付模块
         等待查询结果,省略银行网关
end note
结算模块 <- 银行支付模块 :返回银行出账和入账流水
结算模块 -> 账户模块 :记账指令
activate 账户模块
账户模块 -> 账户模块 :对目标账户充值
结算模块 -> 账户模块 :返回记账结果
deactivate
收银台 <- 结算模块 :返回结算结果
end
充值提现模块 <- 收银台 :返回线上充值结果
@enduml