@startuml
充值提现模块 -> 支付模块 :请求银行入账流水
note over 支付模块
          等待查询结果,省略银行网关
end note
充值提现模块 <- 支付模块 :返回银行入账流水

group 线下转入结算
充值提现模块 -> 结算模块 :线下转入结算指令
结算模块 -> 账户模块 :记账指令
activate 账户模块
账户模块 -> 账户模块 :对目标账户充值
结算模块 <- 账户模块 :返回记账结果
充值提现模块 <- 结算模块 :返回结算结果
deactivate
end
@enduml